## **INTRODUÇÃO**

No experimento apresentado, o conceito de herança de classes foi ambientado na matemática, especificamente ao estudo de matrizes. O intuito da atividade é justamente o de abordar a relação matemática entre diferentes tipos de matrizes e ver como as propriedades das matrizes se aplicam e mantém entre os diferentes tipos.

---

## **CÓDIGO**

##### ***Classe para matrizes***

Nesse caso, como classe mãe, iremos definir uma classe associada à matrizes e operações matriciais.

In [1]:
import numpy as np

class Matriz: 
    def __init__(self, valores):
        self.valores = valores
        self.lin = len(valores)
        self.col = len(valores[0])

    def __add__(self, outra_matriz): 
        if self.lin != outra_matriz.lin or self.col != outra_matriz.col:
            return f"As matrizes não possuem as mesmas dimensões"
        else:
            matriz_soma = np.zeros((self.lin, self.col))
            for i in range (self.lin):
                for j in range (self.col):
                    matriz_soma[i][j] = self.valores[i][j] + outra_matriz.valores[i][j]
            return Matriz(matriz_soma)
        
    def __sub__(self, outra_matriz):
        if self.lin != outra_matriz.lin or self.col != outra_matriz.col:
            return f"As matrizes não possuem as mesmas dimensões"
        else:
            matriz_sub = np.zeros((self.lin, self.col))
            for i in range (self.lin):
                for j in range (self.col):
                    matriz_sub[i][j] = self.valores[i][j] - outra_matriz.valores[i][j]
        return Matriz(matriz_sub)
    
    def __matmul__(self, outra_matriz):
        if self.col != outra_matriz.lin:
            return f"As matrizes não possuem dimensões válidas"
        else:
            matriz_mult = np.zeros((self.lin, outra_matriz.col))
            for i in range (self.lin):
                for j in range (outra_matriz.col):
                    for k in range (self.col):
                        matriz_mult[i][j] += self.valores[i][k] * outra_matriz.valores[k][j]
            return Matriz(matriz_mult)   
        
    def __mul__(self, escalar):
        if isinstance(escalar, (int, float)):  
            matriz_mult = np.zeros((self.lin, self.col))
            for i in range (self.lin):
                for j in range (self.col):
                    matriz_mult[i][j] = self.valores[i][j] * escalar
            return Matriz(matriz_mult)
        else:
            return "Insira um valor válido."
    

    def transposta(self):
        transposta = np.zeros((self.col, self.lin))
        for i in range (self.lin):
            for j in range (self.col):
                transposta[j][i] = self.valores[i][j]
        return Matriz(transposta)

    def mostrar_matriz(self):
        for linha in self.valores:
            print(linha)

Definindo duas matrizes ("matriz1" e "matriz2"), podemos mostrar a utilização da classe a partir de seus métodos, como:

In [2]:
matriz1 = Matriz([[1, 2], [3, 4]])
matriz2 = Matriz([[5, 6], [7, 8]])

* Método para printar as matrizes:

In [3]:
print("Matriz 1:")
matriz1.mostrar_matriz()
print()

print("Matriz 2:")
matriz2.mostrar_matriz()
print()

Matriz 1:
[1, 2]
[3, 4]

Matriz 2:
[5, 6]
[7, 8]



* Método para somar as matrizes:

In [4]:
soma = matriz1 + matriz2
print("Soma das matrizes:")
soma.mostrar_matriz()

Soma das matrizes:
[6. 8.]
[10. 12.]


* Método para subtrair as matrizes:

In [5]:
subtracao = matriz1 - matriz2
print("Subtração das matrizes:")
subtracao.mostrar_matriz()

Subtração das matrizes:
[-4. -4.]
[-4. -4.]


* Método para multiplicar as matrizes:

In [6]:
multiplicacao = matriz1 @ matriz2
print("Multiplicação das matrizes:")
multiplicacao.mostrar_matriz()

Multiplicação das matrizes:
[19. 22.]
[43. 50.]


* Método para multiplicar as matrizes por um escalar:

In [7]:
multiplicacao_escalar = matriz1 * 5
print("Multiplicação da matriz por um escalar:")
multiplicacao_escalar.mostrar_matriz()

Multiplicação da matriz por um escalar:
[ 5. 10.]
[15. 20.]


* Método para transpor as matrizes:

In [8]:
print("Matriz 1 transposta:")
matriz1_T = matriz1.transposta()
matriz1_T.mostrar_matriz()
print()
print("Matriz 2 tranposta:")
matriz2_T = matriz2.transposta()
matriz2_T.mostrar_matriz()

Matriz 1 transposta:
[1. 3.]
[2. 4.]

Matriz 2 tranposta:
[5. 7.]
[6. 8.]


##### ***Classe para matrizes identidade***

Já aqui, criamos a nossa primeira classe filha focando nas matrizes identidade.

In [9]:
class Matriz_Identidade(Matriz):
    def __init__(self, n):
        identidade = np.zeros((n, n))
        for i in range (n):
            for j in range (n):
                if i == j:
                    identidade[i][j] = 1
                else:
                    identidade[i][j] = 0
        print(f"Identidade {n}x{n}:")
        super().__init__(identidade)  
    def verificar_identidade(self):
        for i in range(self.lin):
            for j in range(self.col):
                if i == j and self.valores[i][j] != 1:
                    return False
                elif i != j and self.valores[i][j] != 0:
                    return False
        return True

Podemos criar uma matriz identidade 10x10, por exemplo:

In [10]:
matriz_I = Matriz_Identidade(10)
matriz_I.mostrar_matriz()

Identidade 10x10:
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


E analisar se uma matriz é realmente uma identidade:

In [11]:
matriz_II = Matriz_Identidade(8)
matriz_II.mostrar_matriz()
matriz_II.verificar_identidade()

Identidade 8x8:
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 1.]


True

##### ***Classe para matrizes diagonais***

Para a nossa segunda classe filha, vamos focar nas matrizes diagonais e utilizar seus métodos, como:

In [12]:
class Matriz_Diagonal(Matriz):
    def __init__(self, n):
        diagonal = np.zeros((n, n))
        valores = []
        linha = 1
        for _ in range (n):
            valor = float(input(f"Digite o valor {linha}x{linha} da sua matriz"))
            valores.append(valor)
            linha += 1
        for i in range (n):
            for j in range (n):
                if i==j:
                    diagonal[i][j] = valores[i]
                else:
                    diagonal[i][j] = 0
        print(f"Matriz diagonal {n}x{n}:")
        super().__init__(diagonal)

    def inverter_diagonal(self):
        inversa = np.zeros((self.lin, self.col))
        for i in range(self.lin):
            if self.valores[i][i] == 0:
                return "Não é possível inverter pois há um elemento 0 na diagonal"
            inversa[i][i] = 1 / self.valores[i][i]
        return Matriz(inversa)
    
    def somar_diagonal(self):
        soma = 0
        for i in range (self.lin):
            soma += self.valores[i][i]
        return soma


Criar uma matriz diagonal do tamanho e números desejados:

In [13]:
matriz_diagonal = Matriz_Diagonal(5)
matriz_diagonal.mostrar_matriz()

Matriz diagonal 5x5:
[1. 0. 0. 0. 0.]
[0. 2. 0. 0. 0.]
[0. 0. 3. 0. 0.]
[0. 0. 0. 4. 0.]
[0. 0. 0. 0. 5.]


Fazer a inversa dessa diagonal:

In [14]:
matriz_diagonal_inversa = matriz_diagonal.inverter_diagonal()
matriz_diagonal_inversa.mostrar_matriz()

[1. 0. 0. 0. 0.]
[0.  0.5 0.  0.  0. ]
[0.         0.         0.33333333 0.         0.        ]
[0.   0.   0.   0.25 0.  ]
[0.  0.  0.  0.  0.2]


Ou até calcular a soma desses valores presentes na diagonal da matriz:

In [15]:
matriz_diagonal.somar_diagonal()

np.float64(15.0)

---

## **CONCLUSÃO**

A implementação da herança no contexto de matrizes demonstrou como as propriedades das matrizes podem ser aplicadas e utilizadas para realizar a formação de outros diferentes tipos de matrizes mantendo as suas propriedades e operações. Além disso, foi válido o uso da herança de classes no contexto das matrizes dada a estruturação mais coesa e funcional do código, minimizando a ocorrência de redundâncias.

---

## **REFERÊNCIAS**

**[1]** CASSAR, Daniel. Redes Neurais e Algoritmos Genéticos. 2025. Material de Aula.

**[2]** WASQUES, Vinicius. Álgebra Linear Computacional. 2024. Material de Aula.